model:
  base_learning_rate: 4.5e-6
  target: MaskVQ.mask_vqgan.VQModel
  params:
    embed_dim: 32
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 128
      resolution: 128
      in_channels: 1
      out_ch: 1
      ch: 32
      ch_mult: [ 1,1,2,2,4]
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: MaskVQ.mask_loss.LabelLoss
      params:
        codebook_weight: 1.0

data:
  target: MaskVQ.dataloader.DataModuleFromConfig
  params:
    batch_size: 128
    num_workers: 8
    train:
      target: MaskVQ.dataloader.CustomTrain
      params:
        root_dir: # To be provided
        size: 128
    validation:
      target: MaskVQ.dataloader.CustomTest
      params:
        root_dir: # To be provided
        size: 128
